#!/usr/bin/env bash

pass="123" # This should be unique for every client-server pair/channel
host="0.0.0.0"
port="56622"

# Loop makes sure connection is resumed if closed
while :;do
  while read -re ;do
    echo "${REPLY}" | gpg --batch --quiet --armor --output - --passphrase "${pass}" --symmetric - 2>/dev/null
  done | nc "${host}" "${port}"
done
